# File: .github/workflows/build.yml

name: Build .NET Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # or your target version

    - name: Restore dependencies
      run: dotnet restore /TestFApp1/TestFApp1.sln

    - name: Build
      run: dotnet build /TestFApp1/TestFApp1.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test /TestFApp1/TestFApp1.sln --no-build --verbosity normal
